### ISSUE TITLE
Add support for Tri colour LEDs

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-pyhelper#101]
Add support for Tri colour LEDs as for the Finestra in #100 and the syncrobit

**Comment by shawaj** [comment]
The current structure for a variant is:
```
variant_definitions = {
    # Nebra Indoor Hotspot Gen1
    'NEBHNT-IN1': {
        'FRIENDLY': 'Nebra Indoor Hotspot Gen 1',
        'APPNAME': 'Indoor',
        'SPIBUS': 'spidev1.2',
        'KEY_STORAGE_BUS': '/dev/i2c-1',
        'RESET': 38,
        'MAC': 'eth0',
        'STATUS': 25,
        'BUTTON': 26,
        'ECCOB': True,
        'TYPE': 'Full',
        'CELLULAR': False,
        'FCC_IDS': ['2AZDM-HNTIN'],
        'CONTAINS_FCC_IDS': ['2AHRD-EPN8531', '2AB8JCSR40', '2ARPP-GL5712UX'],
        'IC_IDS': ['27187-HNTIN'],
        'CONTAINS_IC_IDS': []
        },
```

For status LEDs I'm thinking something like:
`'STATUS': [R, G, B],`

Where R, G and B are the GPIO for each LED red green blue.

If you only have a single status LED you just put one in the array and colour doesn't matter. If you have 3 it needs to be in r, g, b order and we can then do some more complicated lighting patterns.

What do you think @NebraLtd/developers  ?

**Comment by shawaj** [comment]
For neopixel LEDs we will need a different strategy or may not be able to support.

**Comment by kashifpk** [comment]
@shawaj - I think we should at least add LED type so the value in `STATUS` field can be parsed accordingly. If `STATUS_TYPE` is not set then `STATUS` is assumed to be single numeric value for a single GPIO pin. Otherwise STATUS parsing should be dependent on STATUS_TYPE. This should keep us backwards compatible and allow flexibility in type of LEDs we want to use.

**Comment by shawaj** [comment]
I like that, good plan @kashifpk 

In theory with a multi colour it could have one of the LEDs as a fallback in `STATUS` if for whatever reason there is an issue
