### ISSUE TITLE
Case for increasing linter max-line-length from 80 to 120

### ISSUE THREAD

**Issue by kashifpk** [NebraLtd/hm-pyhelper#105]
# Issue

Current linter max line length of 80 characters causes unnecessary code fragmentation. In order to please the linter sometimes the resulting code is even harder to understand which is contrary to why we lint. 

## Example:

Dicts with descriptive key names and medium sized values:

```python
request_payload = {
    ADD_GATEWAY_TXN_NAME_KEY: payload[ADD_GATEWAY_TXN_PAYLOAD_KEY]['destination_name'],
    'serial_number': payload[SERIAL_NUMBER_KEY]
}
```

Line 2 of the above is > 80 chars so for the linter it would need to be re-written as:

```python
request_payload = {
    ADD_GATEWAY_TXN_NAME_KEY:
    payload[ADD_GATEWAY_TXN_PAYLOAD_KEY]['destination_name'],
    'serial_number': payload[SERIAL_NUMBER_KEY]
}
```

But this one becomes confusing to read as one key value pair is on 2 lines while the next one is on a single line, so we format it further like:

```python
request_payload = {
    ADD_GATEWAY_TXN_NAME_KEY:
    payload[ADD_GATEWAY_TXN_PAYLOAD_KEY]['destination_name'],
    
    'serial_number':
    payload[SERIAL_NUMBER_KEY]
}
```
This results in both readable and liner-acceptable code. However this is far less readable (specially for dicts where key and start of value are expected to be on the same line) than the initial version.

To avoid such scenarios, devs are tempted to use shorter variable/constant/key names which again is bad for readability. 

# Solution

Most modern IDEs now have at least 120 characters of code area visible even with side bars etc. Older editors like VIM don't even suffer from this as they have more screen real-state available. Increasing the `max-line-length` to `120` is a good balance between readability and fewer code formatting woes.

**Comment by kashifpk** [comment]
Revising my estimate on VS-code and on a 24 inch 4K monitor I have 100 characters of code length visible with sidebars. So can increase by 20 characters. Although have to consider it's effect on laptop users?

Now I'm not too sure about this but keeping this ticket open to get opinion from @NebraLtd/developers

**Comment by shawaj** [comment]
We should probably unify this across our repos as well as some seem to be set to 80 and others to different values

**Comment by MuratUrsavas** [comment]
Laptop user here with 17" FHD. I'm capable to go 140 under normal circumstances and more with hidden sidebar. 80 is too low and is a legacy of century old CRT displays. I second at least 120 chars.

**Comment by vpetersson** [comment]
I don't mind 80. I think it forces the user to write more readable code with sensible newlines. Yes, it stems from CRT etc but it has stuck around for a reason.

**Comment by marvinmarnold** [comment]
@vpetersson I have been enforcing long_verbose_variable_names in code reviews. Sometimes I've found myself renaming things to be shorter but harder to understand just to adhere to line length.

**Comment by vpetersson** [comment]
Yeah fair. We can expand it a bit but i definitely want to enforce something. Maybe 100 is OK. 140 seems a bit too much imho.

**Comment by kashifpk** [comment]
Yeah 100 would still be an improvement while still keeping the code readable. If we have a consensus then this will need to be updated across all repos.

**Comment by kashifpk** [comment]
Changes done (PRs open) for hm-pyhelper, hm-diag, hm-dashboard, Hotspot-Production-Tool and helium-miner-softare. For hm-config there are considerably more changes required to code base to pass flake8 so that should be done as part of refactoring hm-config code.
