### ISSUE TITLE
The button on RAK devices are not working

### ISSUE THREAD

**Issue by MuratUrsavas** [NebraLtd/hm-pyhelper#125]
The button should enable diagnostics and probably mapped incorrectly right now.

**Comment by shawaj** [comment]
Yes definitely wrong GPIO if Bluetooth not activating

I still need to test the Sensecap and Finestra ones too to confirm they are correct

**Comment by MuratUrsavas** [comment]
I've traced the circuit quickly before "All Hands" and seen the but again this information is conflicting with the official RAK docs. So I need to check the behavior while the device is alive.

**Comment by MuratUrsavas** [comment]
Looks like the tracing is correct, but the pin is not acting as on/off (The range is 2,7-3,3V). This could be happening due to incorrect GPIO settings. Will investigate it further today.

**Comment by marvinmarnold** [comment]
@MuratUrsavas is this really in QA?

**Comment by MuratUrsavas** [comment]
@marvinmarnold Yes. I'd been pushed the release to the testnet right after merging it to the master and informed Kevin about it. dev-3 fleet also includes this fix.

**Comment by marvinmarnold** [comment]
But I thought the RAK button still wasn't working per: https://github.com/NebraLtd/hm-config/issues/170

The hardware-definitions updates seem like a partial fix. Basically, this seems like a duplicate of https://github.com/NebraLtd/hm-config/issues/170 and both still need more work.

**Comment by MuratUrsavas** [comment]
Yes, I'd thought these are two separate issues as they are belonging two different repos (hm-pyhelper and hm-config). This one doesn't need further action and can be closed as I've approved it by physical measurement. We can fix NebraLtd/hm-config#170 separately.

**Comment by marvinmarnold** [comment]
In that case, this title should be updated to something more specific like 'update hardware definitions mappings for RAK button`. The description for this task also needs be updated since the button does not currently enable diagnostics/pairing.

That said, I'd like us to avoid tickets that are framed around implementation details (eg updating mappings files), and we should make tickets deliver an entire feature to the user (eg can use button to start advertisement). The way we are working, it is also normal for us to have tickets that are defined in one repo, but work is also needed in others.

**Comment by MuratUrsavas** [comment]
So how do we handle multi-repo tickets? GitHub doesn't support it.

And should we close NebraLtd/hm-config#170 and continue on this one or update the titles and close this one?

**Comment by marvinmarnold** [comment]
A single github issue/ticket can be addressed through multiple PRs, even if they are in different repos. We are manually moving issues through the swimlanes on Zenhub anyways, so there's no complications there. https://github.com/NebraLtd/product-management is also sometimes used to track issues that touch multiple repos.

No strong opinion on how to handle this case. But at this moment, hm-config#170 has more details so might be more helpful to keep.

**Comment by MuratUrsavas** [comment]
Let's close this one and follow the rest on 170. For the upcoming cases we'd use single issues for multiple repos.
