### ISSUE TITLE
Radxa Zero reset pin

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-pyhelper#150]
Radxa Zero has an ADC on pin 15 (which on the light we are using for reset pin for concentrator).

We will need to make a minor modification to the light hardware to move this to pin 11 or 13.

I'll double check with RockPi but I don't think you can change that to a GPIO as it's hard wired to the ADC chip by the looks of it.

Ref https://wiki.radxa.com/Zero/hardware/gpio
Also see #149

**Comment by MuratUrsavas** [comment]
The fix has been introduced in https://github.com/NebraLtd/hardware-designs/pull/7

**Comment by MuratUrsavas** [comment]
Closed on behalf of NebraLtd/hardware-designs#2
