### ISSUE TITLE
Bring gateway-mfr-rs up-to-date

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-pyhelper#164]
Related to: https://github.com/NebraLtd/hm-pyhelper/pull/148
To align with upstream, we need to upate gateway-mfr-rs, some parts of the api has changed.
We can make it generic like helium. For that we might have to introduce following:
```
SWARM_KEY_URI eg "ecc://i2c-1:96?slot=0"
```
This contains all the information that we might need for swarm key or any other purpose. eg. type, bus, address, key slot.
we can keep the old ECC_STORAGE_BUS for sometime.

**Acceptance Criterion**
- Use latest gateway-mfr-rs 0.2.1

**Comment by posterzh** [comment]
**`SWARM_KEY_URI` format:**

`ecc:<dev>[:address][?slot=<slot>]`
- `dev` the device file name (usually begins with i2c or tty)
- `address` the bus address (default 96)
- `slot` the slot to use for key lookup/manipulation (default: 0)

**Comment by vpetersson** [comment]
Given that we bundle `gateway_mfr` with this repo, we should be able to make this fully transactional.

**Comment by posterzh** [comment]
Related with https://github.com/NebraLtd/hm-pyhelper/pull/148

**Comment by marvinmarnold** [comment]
@posterzh can you recommend a way for us to validate that these changes are working in the fleet?

**Comment by posterzh** [comment]
@marvinmarnold 
Working diagnostics page is the obvious proof.
- Animal name comes from the [ECC public key](https://github.com/NebraLtd/hm-diag/blob/fccf704b658d8e7fcd8582e524499032ff503131/hw_diag/tasks.py#L36-L41). The updated [get_public_keys_rust](https://github.com/NebraLtd/hm-diag/blob/5a021ebce3827e0f67e708eb8af7d4eabc346df5/hw_diag/utilities/hardware.py#L288) is used under the hood while getting the animal name.
- "Ecc Detected: True" comes from updated [detect_ecc()](https://github.com/NebraLtd/hm-diag/blob/fccf704b658d8e7fcd8582e524499032ff503131/hw_diag/tasks.py#L35) method.

If `get_public_keys_rust()` is broken while developing, even the `diagnostics` service couldn't start.

**Comment by marvinmarnold** [comment]
Thanks @posterzh. @KevinWassermann94 can you work with Wayne to confirm the diagnostics page is showing the correct public key for devices running the newest release?

**Comment by posterzh** [comment]
@marvinmarnold @KevinWassermann94 The version of `gateway_mfr_rs` can only be checked in the SSH.
Running `/opt/python-dependencies/hm_pyhelper/gateway_mfr --version` in the diagnostics console should give `gateway_mfr 0.2.1` as the response.

**Comment by KevinWassermann94** [comment]
@posterzh Thanks Zhang, good work! This is working
