### ISSUE TITLE
Add COTX X3 hotspot support

### ISSUE THREAD

**Issue by MuratUrsavas** [NebraLtd/hm-pyhelper#165]
**Acceptance Criteria**
* All hardware definitions and necessary information has to be defined in `hardware_definitions.py`.

**Comment by MuratUrsavas** [comment]
cc @shawaj

**Comment by shawaj** [comment]
@MuratUrsavas have you got one there? Can send if not

**Comment by shawaj** [comment]
Also see #121

**Comment by MuratUrsavas** [comment]
@shawaj Thanks. You'd sent one, couple months ago. Already dissected, and added to hm-pyhelper. Just waiting for sprint planning to happen :wink:

**Comment by MuratUrsavas** [comment]
It'll be cool if we could add "powered by Nebra" logo to the status display :smile:

**Comment by MuratUrsavas** [comment]
Done! (ref: NebraLtd/helium-miner-software#465)
