### ISSUE TITLE
Rename hardware definitions

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-pyhelper#171]
Format:
`vendor-model`

Acceptance Criteria:
- [ ] All current hardware variants need to be kept
- [ ] Duplicate hardware variants and rename to new format
- [ ] nebra-indoor1
- [ ] nebra-indoor2
- [ ] nebra-outdoor1
- [ ] rak-fl1
- [ ] helium-fl1
- [ ] sensecap-fl1
- [ ] panther-fl1
- [ ] finestra-fl1
- [ ] pisces-fl1
- [ ] cotx-fl1
- [ ] PR Open, not required to be pushed

**Comment by pritamghanghas** [comment]
according to @KevinWassermann94, only these translations matter:
'NEBHNT-IN1' -> 'nebra-indoor1'
'NEBHNT-OUT1' -> 'nebra-outdoor1'
'NEBHNT-HHRK4' -> 'nebra-indoor2'
'NEBHNT-HHRK4-OUT' -> 'nebra-outdoor2'
'COMP-RAKHM' -> 'rak-v1'
'COMP-HELIUM' -> 'helium-v1'
'COMP-SENSECAPM1' -> 'senscap-v1'
'COMP-PANTHERX1' -> 'panther-v1'
'COMP-FINESTRA' -> 'finestra-v1'
'COMP-PISCESP100' -> 'pisces-v1'
'COMP-COTX3' -> 'cotx3-v1'

**Comment by KevinWassermann94** [comment]
@pritamghanghas As we figured out we should also create these for the light hotspots.
The RasPi one should be `nebra-light1` and the RockPi `nebra-light2`

**Comment by pritamghanghas** [comment]
@KevinWassermann94 whats the deal with last ac "PR Open, not required to be pushed". Open how long? What will be a trigger to merge?

**Comment by vpetersson** [comment]
We need to time this with the fleet renaming. While we do have pinned releases it's to avoid accidentally bumping to this release.

**Comment by marvinmarnold** [comment]
@pritamghanghas going to add `fl` to the fleets instead of `v`

**Comment by pritamghanghas** [comment]
increased points from 1 to 3. As it took lot of iterations and careful testing that everything is good.

**Comment by marvinmarnold** [comment]
@KevinWassermann94 can we get customer support to validate this in testnet?
