### ISSUE TITLE
Read firmware version from miner API

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-pyhelper#2]
* Add functionality to read firmware version from Miner API
* Check what the latest GA version is
* Create new issues in other repos that need to be updated to reflect this new logic.

Once done, adopt this in the relevant repos (replaces https://github.com/NebraLtd/hm-diag/issues/89).

**Comment by marvinmarnold** [comment]
New issues have been created for follow up work so this can be closed:
- https://github.com/NebraLtd/hm-config/issues/120
- https://github.com/NebraLtd/hm-diag/issues/192
- https://github.com/NebraLtd/hm-miner/issues/47
