### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-pyhelper#34]
The release process for this repo is not obvious unless you've done it before. Let's add documentation in the README so any developer can easily contribute. Most recently, the process I attempted failed to push a release to PyPi. These were the steps I took.

1. Open PR and tag commit: `git tag v0.0.x -a`
2. Rebase and merge
3. [Create a new release](https://github.com/NebraLtd/hm-pyhelper/releases/new)
  * Add description of recent changes
  * Add link to PyPi release

I then tried deleting the tag, pulling master locally, and retagging that. After pushing the new [v0.8.9](https://github.com/NebraLtd/hm-pyhelper/tree/v0.8.9) tag, PyPi still didn't release.

**Comment by shawaj** [comment]
@marvinmarnold you have to actually release the tag for it to push to PyPI

https://github.com/NebraLtd/hm-pyhelper/releases/new
