### ISSUE TITLE
Raise proper exceptions on RPC calls

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-pyhelper#38]
We don't have proper exception handing when communicating to the miner over RPC. 

Case in point [here](https://github.com/NebraLtd/hm-diag/blob/master/hw_diag/tasks.py#L37). We need to be able to wrap this around a try/except with proper handing.

Related PR:
https://github.com/NebraLtd/hm-diag/pull/186

**Comment by marvinmarnold** [comment]
@robputt I'm not clear if this was closed by https://github.com/NebraLtd/hm-pyhelper/pull/45. Can you please take a look and give your opinion about next steps?

**Comment by marvinmarnold** [comment]
This can be closed now. Some follow up work to catch the exceptions: https://github.com/NebraLtd/hm-diag/issues/204
