### ISSUE TITLE
is_rockpi isn't called on in provision_key()

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-pyhelper#72]
We need to refactor the `provision_key()` function to use the `run_gateway_mfr()` function rather than trying to invoke `gateway_mfr` by itself to make things DRY and also work on the RockPi.

Right now, because we're running `gateway_ mfr` directly, we don't call on the `is_rockpi()` function, and are therefore not taking the different I2C interface into account.

**Comment by shawaj** [comment]
Closed by https://github.com/NebraLtd/helium-miner-software/pull/286
