### ISSUE TITLE
Use dbus or jsonrpc to create miner generated AddGateway transaction

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-pyhelper#91]
**Notes**
- hm-config logic: https://github.com/NebraLtd/hm-config/blob/900aeed353fb9729b49bca97d7da8a9abf0a2029/gatewayconfig/bluetooth/characteristics/add_gateway_characteristic.py#L48
- RPC code: https://github.com/helium/miner/blob/b9d2cd108cdcc864b641ccf4209f790b1461926d/src/jsonrpc/miner_jsonrpc_txn.erl#L31

**Acceptance criteria**
- Method should accept a specific wallet to generate the transaction for
- Throw an exception to indicate error
- Reusable logic added to hm-pyhelper to generate AddGateway transaction
- Confirm fee and amount are static values, and what their exact values should be
- Returned format should [match](https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/hotspot-integration-testing#generate-an-add-hotspot-transaction) 
```
{
  "address": "11TL62V8NYvSTXmV5CZCjaucskvNR1Fdar1Pg4Hzmzk5tk2JBac",
  "fee": 65000,
  "mode": "full",
  "owner": "14GWyFj9FjLHzoN3aX7Tq7PL6fEg4dfWPY8CrK8b9S5ZrcKDz6S",
  "payer": "138LbePH4r7hWPuTnK6HXVJ8ATM2QU71iVHzLTup1UbnPDvbxmr",
  "staking fee": 4000000,
  "txn": "CrkBCiEBrlImpYLbJ0z0hw5b4g9isRyPrgbXs9X+RrJ4pJJc9MkSIQA7yIy7F+9oPYCTmDz+v782GMJ4AC+jM+VfjvUgAHflWSJGMEQCIGfugfLkXv23vJcfwPYjLlMyzYhKp+Rg8B2YKwnsDHaUAiASkdxUO4fdS33D7vyid8Tulizo9SLEL1lduyvda9YVRCohAa5SJqWC2ydM9IcOW+IPYrEcj64G17PV/kayeKSSXPTJOMCEPUDo+wM="
}
```

**Comment by marvinmarnold** [comment]
After some thought, RPC is more dev friendly than dbus. These steps, create a new AddGateway transaction over RPC. Next step is to decode the protobuf and generate a JSON response matching [docs](https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/hotspot-integration-testing/#generate-an-add-hotspot-transaction.

**Create dev wallet**
- Download most recent wallet CLI: https://github.com/helium/helium-wallet-rs/tags
- Create wallet: `./helium-wallet create basic --output test.key`

**Create transaction**
```
$ balena ssh UUID diagnostics

# apt update
# apt install jq
# curl -X POST \
     -H 'Content-Type: application/json' \
     -d '{"jsonrpc":"2.0","id":"1","method":"txn_add_gateway","params":{"owner": "14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47"}}' \
     http://helium-miner:4467 | \
     jq -r '.result.result' 

CpgBCiEBwPbb63LQD8x/m/ZDLLyOLgtxypQIjh+xPPS+d8g/i24SIQDzXDMN/K3ALMFd+/bs333PGzlElIc1CYp1qzPx6Fm6ryJIMEYCIQDW9VNmLfvmUjpWGLflWVnPUnhvP5KafCW61DPvOYdanAIhAPRNo7T0Lx3EgZRuPEExYdRBZhTmAbmFo98wX1MlTM6SOMCEPUDI3wI=
```

**Relevant code**

- RPC handling: [helium/miner](https://github.com/helium/miner/blob/b9d2cd108cdcc864b641ccf4209f790b1461926d/src/jsonrpc/miner_jsonrpc_txn.erl#L31)
- Tranaction creation: [helium/blockchain-core](https://github.com/helium/blockchain-core/blob/608a2d20b35aaa21ba731add674c7f772b6e65e6/src/blockchain.erl#L2294)
- Serialization: [helium/blockchain-core](https://github.com/helium/blockchain-core/blob/3cd6bca6c5595a1363a9bbd625ef254383a4141b/src/transactions/blockchain_txn.erl#L160)
- Protobuf: [helium/proto](https://github.com/helium/proto/blob/6dc60a9933628c3baf9d2f5386481f20a5d79bb8/src/blockchain_txn_add_gateway_v1.proto#L1)

**Comment by marvinmarnold** [comment]
I am still confused about why the payload returned by the RPC endpoint is [stripping the leading 0 byte](https://pastebin.com/ut4LBp0k) of both `owner` and `gateway`. I've asked for clarification on Discord. @posterzh any chance you can link to the spot in the app code where it handles the AddGateway response, this might give me a clue about what's going on too.

That said, now that I understand the payloads better, I don't think we actually need to deserialize the fields that are problematic. [These](https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/hotspot-integration-testing/#generate-an-add-hotspot-transaction) are the fields we have been referencing and how they will be populated.

- "address": Miner's address. From /json
- "fee": integer that is not an issue to decode
- "mode": Always "full" / can probably ignore
- "owner": Supplied to pyhelper when invoking
-  "payer": Supplied to pyhelper when invoking
- "staking fee": integer that is not an issue to decode
- "txn": As far as I can tell, this is the full RPC response before deserialization. We can echo this out even if we have trouble deserializing certain fields within it.

@vpetersson has iHub shared a sample output that they are looking for? I'd like to confirm that our planned output is what they want. If not I can ask them for it.

**Comment by vpetersson** [comment]
@marvinmarnold i don't think they have any strong preference for output as long as we can create a CSV file for them with the relevant data. Also, keep in mind that this is the temporary solution -- we want to expose this over an API later so let's not over engineer the spreadsheet production.

**Comment by marvinmarnold** [comment]
Notes in case I need them:

test.py
```
import hm_pyhelper.protos.blockchain_txn_pb2 as blockchain_txn_pb2
# import hm_pyhelper.protos.blockchain_txn_add_gateway_v1_pb2 as blockchain_txn_add_gateway_v1_pb2
import base64
import base58

PAYER = '13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3'
OWNER = '14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47'

# curl -X POST \
#      -H 'Content-Type: application/json' \
#      -d '{"jsonrpc":"2.0","id":"1","method":"txn_add_gateway","params":{"owner": "14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47", "payer": "13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3"}}' \
#      http://helium-miner:4467 | \
#      jq -r '.result.result' 

# curl -X POST \
#      -H 'Content-Type: application/json' \
#      -d '{"jsonrpc":"2.0","id":"1","method":"txn_add_gateway","params":{"owner": "14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47", "payer": "13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3"}}' \
#      http://helium-miner:4467

# rpc_encoded = "CpgBCiEBwPbb63LQD8x/m/ZDLLyOLgtxypQIjh+xPPS+d8g/i24SIQCWHS+l8MNjHEAJ1m+qBE32AQqbxtyeiXKNQyiomPhbXCJIMEYCIQCO5O1WOykypJcIIhw7EYs2Au5Mm+82mVfwL8f0FXL7MQIhAOOfCMUkO/ccT0OVcoZ1J26HQ00MbUqDW0mHvnyy+dZpOMCEPUDI3wI="
# rpc_encoded = "CpcBCiEBwPbb63LQD8x/m/ZDLLyOLgtxypQIjh+xPPS+d8g/i24SIQCWHS+l8MNjHEAJ1m+qBE32AQqbxtyeiXKNQyiomPhbXCJHMEUCIHaxVH5lKDQD7jGUiTf6QiicXUtULkoqxjsvADtL/vn6AiEApkVHVeJ2jpveUTbTGLpAvP+MBxNTNT/PChGaUu6T2go4wIQ9QMjfAg=="
# new miner
# rpc_encoded = "CpYBCiEBwPbb63LQD8x/m/ZDLLyOLgtxypQIjh+xPPS+d8g/i24SIQB8XdzWqrIF201DNKHpXKFtsMtgvZeqBBc1wOk9sV2j4SJGMEQCIE8ouEs76zvhdy3xilw15+gwTh099ac4HyzOQ5t/OmCgAiBLeYznWbgdrVAqyyFVe1wwl8Q7u0YBRgW4poVN6UTA2TjAhD1AyN8C"
rpc_encoded = "CrwBCiEBwPbb63LQD8x/m/ZDLLyOLgtxypQIjh+xPPS+d8g/i24SIQB8XdzWqrIF201DNKHpXKFtsMtgvZeqBBc1wOk9sV2j4SJIMEYCIQCg9kyao4e1ResDhV58YIThffoGrmQ3TTzEyx05k2qyYwIhANtBCP91uPBfvmhJqndz5vZL+9LDGzBXbudB9tal5O9IKiEBUddrDWQ2XLZU63jsyXNN+QIhRM6Bbfg6vDUtIm372YI4gJL0AUDo+wM="
rpc_decoded = base64.b64decode(rpc_encoded)

wrapped_txn = blockchain_txn_pb2.blockchain_txn()
wrapped_txn.ParseFromString(rpc_decoded)

add_gateway_txn = wrapped_txn.add_gateway
print(add_gateway_txn)
print("Parsed")
owner = base58.b58encode(add_gateway_txn.owner).decode()
payer = base58.b58encode(add_gateway_txn.payer).decode()
gateway = base58.b58encode(add_gateway_txn.gateway).decode()
print(f"owner bytes: {add_gateway_txn.owner}")
decoded_owner = base58.b58encode_check(add_gateway_txn.owner)
print(f"decoded owner: {decoded_owner}")
print(payer)
print(gateway)
decoded_owner = base58.b58encode_check(add_gateway_txn.gateway)
print(f"gateway bytes: {bytes(add_gateway_txn.gateway)}")
print(f"decoded gateway: {decoded_owner}")
# 13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3
# XDZyNpKx47SLGTdYA1gYtiL5DV3qtS7Dhxcz6tMkfKLy
# 19NUZtpAK1atZxvTnG5FUNji7xescmiBvLkmJTGtUKs4C

# RPC request: https://github.com/helium/miner/blob/b9d2cd108cdcc864b641ccf4209f790b1461926d/src/jsonrpc/miner_jsonrpc_txn.erl#L31
# Transaction creation: https://github.com/helium/blockchain-core/blob/608a2d20b35aaa21ba731add674c7f772b6e65e6/src/blockchain.erl#L2294
# Owner b58 -> bin: https://github.com/helium/libp2p-crypto/blob/b94c95ee7c24933bf81a732a1da7cf0be4014750/src/libp2p_crypto.erl#L518
#   calls: https://github.com/helium/libp2p-crypto/blob/b94c95ee7c24933bf81a732a1da7cf0be4014750/src/libp2p_crypto.erl#L547
# base58_to_binary: https://github.com/titan098/erl-base58/blob/c5319e77a8edf8c13a3522928384a65511d26a88/src/base58.erl#L194

print(f"with check {base58.b58decode_check('14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47')}")
print(base58.b58encode_check(b'\x00\x01\xc0\xf6\xdb\xebr\xd0\x0f\xcc\x7f\x9b\xf6C,\xbc\x8e.\x0bq\xca\x94\x08\x8e\x1f\xb1<\xf4\xbew\xc8?\x8bn'))

```

**Comment by marvinmarnold** [comment]
Confirmed this is working with https://github.com/helium/miner/releases/tag/2022.01.26.0.

1. Bumped hm-miner: https://github.com/NebraLtd/hm-miner/commit/024fcbb182ad9499e3a9521f17b29133ebaf8fe0
2. Bumped hm-diag: https://github.com/NebraLtd/hm-diag/commit/0e4c0148362cee156f46e9fe164c9d583540f288
3. Updated local helium-miner-software to include those hashes.
4. Deploy, SSH into diagnostics container, open python shell

```
>>> from hm_pyhelper.miner_json_rpc import MinerClient
>>> c = MinerClient()

# Create transaction with all params
>>> c.create_add_gateway_txn('14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47', '13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3', gateway_address='11wmnCAfvFkdx3Az1hesTsSv9YeBUhs8JZKjCqcs2vmRwRazpBa')
{'gateway_address': '11wmnCAfvFkdx3Az1hesTsSv9YeBUhs8JZKjCqcs2vmRwRazpBa', 'owner_address': '14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47', 'payer_address': '13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3', 'fee': 65000, 'staking_fee': 4000000, 'txn': 'CrwBCiEBwPbb63LQD8x/m/ZDLLyOLgtxypQIjh+xPPS+d8g/i24SIQB8XdzWqrIF201DNKHpXKFtsMtgvZeqBBc1wOk9sV2j4SJIMEYCIQCDLZBvMRHP72o3LMsApX7oh+oboEzbayqMvVgCn0Q4lgIhAL9iDyFqwkH1+1/D5v4PL6FSCSm6CwYqdulS3DRxNSaCKiEBUddrDWQ2XLZU63jsyXNN+QIhRM6Bbfg6vDUtIm372YI4gJL0AUDo+wM='}

# Omit gateway
>>> c.create_add_gateway_txn('14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47', '13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3')

{'gateway_address': '11wmnCAfvFkdx3Az1hesTsSv9YeBUhs8JZKjCqcs2vmRwRazpBa', 'owner_address': '14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47', 'payer_address': '13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3', 'fee': 65000, 'staking_fee': 4000000, 'txn': 'CrsBCiEBwPbb63LQD8x/m/ZDLLyOLgtxypQIjh+xPPS+d8g/i24SIQB8XdzWqrIF201DNKHpXKFtsMtgvZeqBBc1wOk9sV2j4SJHMEUCICVynWJyEU8L9vJcBk08Uh7IVNoh2tVeue58NA6jQY1UAiEA6KpuOj+kdtBWy0aZiMsZ3/6DzVLUunDZTkueZnrChSEqIQFR12sNZDZctlTreOzJc035AiFEzoFt+Dq8NS0ibfvZgjiAkvQBQOj7Aw=='}

# provide incorrect gateway
>>> c.create_add_gateway_txn('14QjC3A5DEH2uFwhDxyBHdFir7YWGG23Fic1wGvkCr6qrWC7Q47', '13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3', gateway_address='invalid')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python-dependencies/hm_pyhelper/miner_json_rpc/client.py", line 115, in create_add_gateway_txn
    txn_gateway_address = get_address_from_add_gateway_txn(
  File "/opt/python-dependencies/hm_pyhelper/miner_json_rpc/client.py", line 167, in get_address_from_add_gateway_txn
    raise MinerMalformedAddGatewayTxn(msg)
hm_pyhelper.miner_json_rpc.exceptions.MinerMalformedAddGatewayTxn: Expected gateway address to be invalid,but is 11wmnCAfvFkdx3Az1hesTsSv9YeBUhs8JZKjCqcs2vmRwRazpBa
```
